---
abstract: 'Easy SMS sending from Catalyst Apps.'
author:
  - 'Martin Atukunda <matlads@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::ScriptRunner: 0
  Catalyst::Test: 0
  FindBin: 0
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
  Test::WWW::Mechanize::Catalyst: 0
  base: 0
  namespace::autoclean: 0
  ok: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-SMS
requires:
  Catalyst::Model::Adaptor: 0
  Moose: 0
  SMS::Send: 0
  strict: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Catalyst-Model-SMS
  repository: http://github.com/matlads/Catalyst-Model-SMS.git
version: 0.3
